services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: claimsphere-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: claimsphere-aspire-dashboard
    ports:
      - "18888:18888"
      - "18889:18889"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

volumes:
  rabbitmq-data:
