<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HealthCare.Claims.DocumentsService.Application\HealthCare.Claims.DocumentsService.Application.csproj" />
    <ProjectReference Include="..\HealthCare.Claims.DocumentsService.Domain\HealthCare.Claims.DocumentsService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
